version: "3.7"

services:
  postgres:
    image: pgvector/pgvector:pg14
    environment:
      - POSTGRES_PASSWORD=AdminAdmin
    networks:
      - data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  postgres_data:
    external: true
    name: postgres_data

networks:
  data:
    external: true
    name: "${DATA_NETWORK}"
