version: "3.7"

services:
  postgres:
    image: pgvector/pgvector:pg14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    networks:
      - data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h 127.0.0.1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

secrets:
  postgres_password:
    external: true
    name: "${STACK_PREFIX}_postgres_password"

volumes:
  postgres_data:
    external: true
    name: "${STACK_PREFIX}_postgres_data"

networks:
  data:
    external: true
    name: "${DATA_NETWORK}"
