version: "3.7"

services:
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    networks:
      - edge
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=AdminAdmin
      - MINIO_BROWSER_REDIRECT_URL=https://${DOMAIN_MINIO_CONSOLE}
      - MINIO_SERVER_URL=https://${DOMAIN_S3}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true

        - traefik.http.routers.s3.rule=Host(`${DOMAIN_S3}`)
        - traefik.http.routers.s3.entrypoints=websecure
        - traefik.http.routers.s3.tls.certresolver=letsencryptresolver
        - traefik.http.services.s3.loadbalancer.server.port=9000

        - traefik.http.routers.minio_console.rule=Host(`${DOMAIN_MINIO_CONSOLE}`)
        - traefik.http.routers.minio_console.entrypoints=websecure
        - traefik.http.routers.minio_console.tls.certresolver=letsencryptresolver
        - traefik.http.services.minio_console.loadbalancer.server.port=9001

volumes:
  minio_data:
    external: true
    name: minio_data

networks:
  edge:
    external: true
    name: "${EDGE_NETWORK}"
