version: "3.8"

services:
  redis:
    image: redis:7-alpine
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--appendfsync", "everysec",
        "--port", "6379"
      ]
    volumes:
      - redis_data:/data
    networks:
      - data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  redis_data:
    external: true
    name: "${TENANT}_${ENV}_redis_data"

networks:
  data:
    external: true
    name: "${DATA_NETWORK}"
