version: "3.7"

services:
  evolution:
    image: evoapicloud/evolution-api:v2.3.7
    command: ["node", "./dist/src/main.js"]
    networks:
      - edge
      - data
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    environment:
      - SERVER_URL=https://${DOMAIN_EVO}
      - DOCKER_ENV=true

      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=72c3ccfa4228772d20c536733b595c

      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/6
      - CACHE_REDIS_PREFIX_KEY=evolution_thermas_prod
      - CACHE_LOCAL_ENABLED=false

      - LOG_LEVEL=ERROR,WARN,INFO
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.evolution.rule=Host(`${DOMAIN_EVO}`)
        - traefik.http.routers.evolution.entrypoints=websecure
        - traefik.http.routers.evolution.tls.certresolver=letsencryptresolver
        - traefik.http.services.evolution.loadbalancer.server.port=8080

volumes:
  evolution_instances:
    external: true
    name: evolution_instances
  evolution_store:
    external: true
    name: evolution_store

networks:
  edge:
    external: true
    name: "${EDGE_NETWORK}"
  data:
    external: true
    name: "${DATA_NETWORK}"
