version: "3.7"

x-evolution-env: &evolution_env
  TZ: ${TZ}
  DOCKER_ENV: "true"
  SERVER_URL: "https://${DOMAIN_EVO}"

  AUTHENTICATION_TYPE: "apikey"

  DATABASE_ENABLED: "true"
  DATABASE_PROVIDER: "postgresql"

  CACHE_REDIS_ENABLED: "true"
  CACHE_LOCAL_ENABLED: "false"
  CACHE_REDIS_PREFIX_KEY: "${EVO_CACHE_PREFIX}"
  EVO_CACHE_REDIS_DB: "${EVO_CACHE_REDIS_DB}"

  LOG_LEVEL: "${EVO_LOG_LEVEL}"

services:
  evolution_api:
    image: evoapicloud/evolution-api:v2.3.7

    entrypoint: ["/bin/sh","-c"]
    command: |
      echo "== Evolution bootstrap starting =="

      export AUTHENTICATION_API_KEY="$(cat /run/secrets/evolution_api_key)"

      export DATABASE_CONNECTION_URI="postgresql://postgres:$(cat /run/secrets/postgres_password)@postgres:5432/evolution_db?schema=evolution_api"
      export DATABASE_URL="$DATABASE_CONNECTION_URI"

      export CACHE_REDIS_URI="redis://:$(cat /run/secrets/redis_password)@redis:6379/${EVO_CACHE_REDIS_DB}"

      echo "== Running migrations =="
      npm run db:deploy

      echo "== Starting Evolution =="
      exec npm run start:prod

    environment:
      <<: *evolution_env

    secrets:
      - evolution_api_key
      - postgres_password
      - redis_password

    networks:
      - edge
      - data

    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

secrets:
  evolution_api_key:
    external: true
    name: thermas_prod_evolution_api_key

  postgres_password:
    external: true
    name: thermas_prod_postgres_password

  redis_password:
    external: true
    name: thermas_prod_redis_password

volumes:
  evolution_instances:
    external: true
    name: thermas_prod_evolution_instances

  evolution_store:
    external: true
    name: thermas_prod_evolution_store

networks:
  edge:
    external: true
    name: "${EDGE_NETWORK}"

  data:
    external: true
    name: "${DATA_NETWORK}"
