version: "3.7"

x-evolution-env: &evolution_env
  TZ: ${TZ}
  DOCKER_ENV: "true"
  SERVER_URL: "https://${DOMAIN_EVO}"

  AUTHENTICATION_TYPE: "apikey"

  DATABASE_ENABLED: "true"
  DATABASE_PROVIDER: "postgresql"

  CACHE_REDIS_ENABLED: "true"
  CACHE_LOCAL_ENABLED: "false"
  CACHE_REDIS_PREFIX_KEY: "${EVO_CACHE_PREFIX}"
  EVO_CACHE_REDIS_DB: "${EVO_CACHE_REDIS_DB}"

  LOG_LEVEL: "${EVO_LOG_LEVEL}"

services:
  evolution_api:
    image: evoapicloud/evolution-api:v2.3.7
    command:
      - sh
      - -lc
      - |
        set -eu;

        # Fail-fast: garante que os secrets existem
        test -f /run/secrets/postgres_password || { echo "ERROR missing postgres_password"; ls -lah /run/secrets || true; exit 1; };
        test -f /run/secrets/redis_password || { echo "ERROR missing redis_password"; ls -lah /run/secrets || true; exit 1; };
        test -f /run/secrets/evolution_api_key || { echo "ERROR missing evolution_api_key"; ls -lah /run/secrets || true; exit 1; };

        POSTGRES_PASSWORD="$$(cat /run/secrets/postgres_password | tr -d '\r\n')";
        AUTHENTICATION_API_KEY="$$(cat /run/secrets/evolution_api_key | tr -d '\r\n')";

        # URL-encode para senha Redis (caso tenha caracteres reservados)
        REDIS_PASSWORD_ENC="$$(node -e "process.stdout.write(encodeURIComponent(require('fs').readFileSync('/run/secrets/redis_password','utf8').trim()))")";

        # Hosts/ports preferencialmente via .env (como no n8n). Fallback compatível com o que já funcionou.
        PG_HOST="$${POSTGRES_HOST:-postgres_postgres}";
        PG_PORT="$${POSTGRES_PORT:-5432}";
        RD_HOST="$${REDIS_HOST:-redis_redis}";
        RD_PORT="$${REDIS_PORT:-6379}";

        # *** SEM SCHEMA ***
        DB_URI="postgresql://postgres:$${POSTGRES_PASSWORD}@$${PG_HOST}:$${PG_PORT}/evolution_db";
        REDIS_URI="redis://:$${REDIS_PASSWORD_ENC}@$${RD_HOST}:$${RD_PORT}/$${EVO_CACHE_REDIS_DB}";

        export AUTHENTICATION_API_KEY="$$AUTHENTICATION_API_KEY";

        # Define os dois: o app e o Prisma
        export DATABASE_CONNECTION_URI="$$DB_URI";
        export DATABASE_URL="$$DB_URI";

        export CACHE_REDIS_URI="$$REDIS_URI";

        exec npm run start:prod

    environment:
      <<: *evolution_env

    networks:
      - edge
      - data

    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

    secrets:
      - evolution_api_key
      - postgres_password
      - redis_password

    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=${EDGE_NETWORK}
        - traefik.http.routers.evolution.rule=Host(`${DOMAIN_EVO}`)
        - traefik.http.routers.evolution.entrypoints=websecure
        - traefik.http.routers.evolution.tls.certresolver=letsencryptresolver
        - traefik.http.services.evolution.loadbalancer.server.port=8080

secrets:
  evolution_api_key:
    external: true
    name: "${TENANT}_${ENV}_evolution_api_key"
  postgres_password:
    external: true
    name: thermas_prod_postgres_password
  redis_password:
    external: true
    name: thermas_prod_redis_password

volumes:
  evolution_instances:
    external: true
    name: "${TENANT}_${ENV}_evolution_instances"
  evolution_store:
    external: true
    name: "${TENANT}_${ENV}_evolution_store"

networks:
  edge:
    external: true
    name: "${EDGE_NETWORK}"
  data:
    external: true
    name: "${DATA_NETWORK}"
